### ISSUE TITLE
anaconda2 errors

### ISSUE THREAD

**Issue by raw937** [jfjlaros/demultiplex#2]
demultiplex demux barcodes.txt demultiplex.fq 
Traceback (most recent call last):
  File "/home/raw937/anaconda2/bin/demultiplex", line 7, in <module>
    from demultiplex.cli import main
  File "/home/raw937/anaconda2/lib/python2.7/site-packages/demultiplex/__init__.py", line 13, in <module>
    from .demultiplex import Extractor, count, demultiplex
  File "/home/raw937/anaconda2/lib/python2.7/site-packages/demultiplex/demultiplex.py", line 6, in <module>
    from fastools import guess_file_format, guess_header_format
  File "/home/raw937/anaconda2/lib/python2.7/site-packages/fastools/__init__.py", line 5, in <module>
    from .fastools import *
  File "/home/raw937/anaconda2/lib/python2.7/site-packages/fastools/fastools.py", line 5, in <module>
    from urllib.error import HTTPError
ImportError: No module named error

**Comment by raw937** [comment]
?
