### ISSUE TITLE
can't run demultiplex with SyntaxError

### ISSUE THREAD

**Issue by AstreChen** [jfjlaros/demultiplex#5]
Hi, 
I have installed the demultiplex with the lastest version. but I cannot run successfully. 
My python version is 3.6.7. Any help?

$ demultiplex -h
Traceback (most recent call last):
  File "/home/hulab/chen/miniconda2/bin/demultiplex", line 6, in <module>
    from demultiplex.cli import main
  File "/home/hulab/chen/miniconda2/lib/python3.6/site-packages/demultiplex/cli.py", line 92
    except IOError , error:
                   ^
SyntaxError: invalid syntax

**Comment by jfjlaros** [comment]
It looks to me that you are using an old version. Could you try to reinstall it?
